import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import cv2
from lmfit import Model

# Import sibling modules relative to this file so the script works from any cwd.
script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.insert(0, script_dir)

import Image_Tools

"""
This script builds the calibration mapping of the Paper UV camera. One can view the mapping as a 2D image, or apply it to a raw DNG image to see the calibrated result. The calibration mapping is stored in "calibration_map.npy" and can be generated by running CalibrationTemplate.py
"""

#loading the calibration data
calibration_file_path=os.path.join(script_dir,"Calibration.csv")
c=Image_Tools.Calibration(calibration_file_path)

# Example: Load and display the calibration map applied to a image
fname="XX.dng"
file_path = os.path.join(script_dir,"..", "Pictures","FHG_Fix", fname)

#To view the calibration map as a 2D image:
image=np.ones((1520, 2028), dtype=np.float64)  

#To view the calibration map applied to a raw DNG image, uncomment below and comment out the above line
#image=CircularBlur.load_DNG(file_path)

image=c.calibrate_image(image)

plt.imshow(image,cmap='gray')

#To save the calibration map as a numpy array, uncomment below
#np.save("calibration_map.npy", image)
#print("Exported calibrated image")


plt.show()

quit()
